server:
  port: 8080 
  session-timeout: 5000
  servlet:
     context-path: /api
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: TRACE
spring:
  application:
    name: MsApp-example
  datasource:
    continue-on-error: false
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: false
  hateoas:
    use-hal-as-default-json-media-type: true
  http:
    converters:
      preferred-json-mapper: jackson
  cloud:
    consul:
      discovery:
        hostname: localhost
        healthCheckPath: ${server.servlet.context-path}/actuator/health
        healthCheckInterval: 30s
        tags: service=orders
        instanceId: ${spring.application.name}-${spring.cloud.consul.config.data-key}
        catalogServicesWatchDelay: 86400000
